apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: server
          image: zermond/hipster-frontend:v0.0.1
          env:
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "PRODUCTSERVICE:4444"
          - name: CURRENCY_SERVICE_ADDR
            value: "CURRSERVICE:4444"
          - name: CART_SERVICE_ADDR
            value: "CARTSERVICE:4444"
          - name: RECOMMENDATION_SERVICE_ADDR
            value: "recommendationservice:8080"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice:50051"
          - name: CHECKOUT_SERVICE_ADDR
            value: "checkoutservice:5050"
          - name: AD_SERVICE_ADDR
            value: "adservice:9555"
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
                - name: "Cookie"
                  value: "shop_session-id=x-readiness-probe"
  selector:
    matchLabels:
      app: frontend